stages:
  - deploy

deploy-cloud-function:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo "${GCLOUD_SERVICE_KEY}" > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud functions deploy rwgps_analysis --region europe-west2 --entry-point HandleRequest --runtime go113 --memory 512MB --trigger-http --allow-unauthenticated --project "${GCLOUD_PROJECT}"
  only:
    - master
